SmartCity_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
   path('',include('credentials.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,
                document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL,
                document_root=settings.MEDIA_ROOT)

Water_app/urls.py
from django.urls import path
from . import views


app_name ='water'


urlpatterns =[
    path('',views.index,name='index')

]

credentials/urls.py
from django.urls import path
from . import views



app_name='credentials'

urlpatterns = [
    
    path('',views.index,name='index'),
    path('signIn',views.signIn,name='signIn'),
    path('logout',views.logout,name='logout'),
    path('mypage',views.myfunction),
    path('method',views.method),
    path('demo',views.demo),

    #ADMIN
    path('Admin',views.admin_index,name='AdminHome'),
    path('addMuninicipality',views.addMuninicipality,name='addMuninicipality'),

    #Municipality
    path('municipality',views.municipalityHome,name='municipalityHome'),
    path('AddWasteBin',views.AddWasteBin,name='AddWasteBin'),
    path('AddCollectionAgent',views.AddCollectionAgent,name='AddCollectionAgent'),

    #Collection Agent
    path('Home',views.collectionAgent_home,name='collectionAgent_home'),


]

templates/basic/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">


    <style>
        #myMap {
            height: 350px;
            width: 380px;
        }
        .bg-info{
            background-color:#FB5B38 !important; 
        }
        
    </style>
    <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzXv05Tg7stti5DyuH1_FmXPWKFS9EkHE&libraries=places&callback=initAutocomplete"
    async defer></script>

<script>
    function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('myMap'), {
            center: { lat: 8.490001, lng: 76.95397 },
            zoom: 18,
            mapTypeId: 'roadmap'
        });
        google.maps.event.addListener(map, 'dblclick', function (e) {
            //alert("Latitude: " + e.latLng.lat() + "\r\nLongitude: " + e.latLng.lng());
            document.getElementById("latitude").value = e.latLng.lat();
            document.getElementById("longitude").value = e.latLng.lng();
            // document.getElementById("myMap").style.display = "none";
            alert("Pickup location Added")
        });
        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        //map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function () {
            searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function () {
            var places = searchBox.getPlaces();

            if (places.length == 0) {
                return;
            }

            // Clear out the old markers.
            markers.forEach(function (marker) {
                marker.setMap(null);
            });
            markers = [];

            // For each place, get the icon, name and location.
            var bounds = new google.maps.LatLngBounds();
            places.forEach(function (place) {
                if (!place.geometry) {
                    console.log("Returned place contains no geometry");
                    return;
                }
                var icon = {
                    url: place.icon,
                    size: new google.maps.Size(71, 71),
                    origin: new google.maps.Point(0, 0),
                    anchor: new google.maps.Point(17, 34),
                    scaledSize: new google.maps.Size(25, 25)
                };

                // Create a marker for each place.
                markers.push(new google.maps.Marker({
                    map: map,
                    icon: icon,
                    title: place.name,
                    position: place.geometry.location
                }));

                if (place.geometry.viewport) {
                    // Only geocodes have viewport.
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }
            });
            map.fitBounds(bounds);
        });
    }

</script>




</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
        {% if admin %}
        <!-- admin header & sidebar -->
        {% include 'admin/admin_navbar.html' %} {% include 'admin/Admin_sidebar.html' %}
        <!-- admin header & sidebar -->
        {% elif municipality %}
        <!-- municipality header & sidebar -->
        {% include 'municipality/municipality_navbar.html' %} {% include 'municipality/municipality_sidebar.html' %}
        <!-- municipality header & sidebar -->
        <!-- municipality header & sidebar -->
        {% elif collectionAgent %}
        <!-- municipality header & sidebar -->
        {% include 'collection_agent/collectionAgent_navbar.html' %} {% include 'collection_agent/collectionAgent_sidebar.html' %}
        <!-- municipality header & sidebar -->
        {% elif user %}
        <!-- municipality header & sidebar -->
        {% include 'user/user_navbar.html' %} {% include 'user/user_sidebar.html' %}
        
        {% else  %}
        <!--  header & sidebar -->
       
        {% include 'basic/navbar.html' %} {% include 'basic/sidebar.html' %}
        <!--  header & sidebar -->
        {% endif %}
        <!-- block page content -->
        {% block content %} {% endblock %}
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.1.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'dist/js/pages/dashboard.js' %}"></script>


    <script>
        function work() {
            console.log("work")
        }
    </script>

    
<script>
    function validateForm(){
        console.log("workld")
        var num = document.getElementById("exampleInpuNumber").value;

        if (num.length != 10){
            return false
        }
        console.log("ss ")
        var name = document.getElementById("exampleInputName").value;
        if (name.length < 3 ){
            return false
        }
    }
</script>
</body>

</html>

templates/basic/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>DEMO PAGE</h1>
</body>
</html>

templates/basic/methods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Methods for Disposal</title>
</head>
<body>
    <h1>Methods for Disposal</h1>
    <ul>
        <li>{{m}}</li>
        <li>Recycling</li>
        <li>Landfills</li>
    </ul>
    
    
</body>
</html>

templates/basic/myhomepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>my home</title>
</head>
<body>
    <h1>my home pages</h1><br>
    <h3>name : {{n}}</h3>
    <h3>contact : {{c}}</h3>
    <img src="static/landing/img/bg_banner2.jpg" alt="">
</body>
</html>

templates/basic/navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'credentials:index' %}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

 
</nav>

templates/basic/sidebar.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-light-purple elevation-4">
    <!-- Brand Logo -->
    <!-- <a href="../../index3.html" class="brand-link">
        <img src="../../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">collection Agent 3</span>
    </a> -->

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{collectionAgent.photo.url}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block"> {{collectionAgent.name}}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <label class="switch" style="margin-left:60px ;">
                    <input type="checkbox" id="change_off" onchange="change_Status()">
                    <span class="slider round"></span>
                </label>
                <label id="online">Online</label>
            </div>
        </div>


        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Home
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="../widgets.html" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Register Account
                            <span class="right badge badge-danger">New</span>
                        </p>
                    </a>
                </li>
 
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

templates/basic/signIn.html
{% extends 'basic/base.html' %} {% load static %} {% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>SignIn</h1>
                </div>
                <!-- <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="">Home</a></li>
                        <li class="breadcrumb-item active">SigIn</li>
                    </ol>
                </div> -->
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-3"></div>
                <div class="col-md-6">


                    <!-- general form elements -->

                    <!-- /.card -->
                    <!-- Horizontal Form -->
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Signin </h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form class="form-horizontal" method="POST">
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="form-group row">
                                    <label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" name="username" class="form-control" id="inputEmail3" placeholder="Email">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
                                    <div class="col-sm-10">
                                        <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="offset-sm-2 col-sm-10">
                                        <div class="form-check">
                                            <!-- <input type="checkbox" class="form-check-input" id="exampleCheck2"> -->
                                            <label class="form-check-label" for="exampleCheck2">Remember
                                                    me</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info">Sign in</button>
                                <button class="btn btn-default float-right"><a href="{% url 'credentials:user_registration' %}">Register</a></button>
                            </div>
                            <!-- /.card-footer -->
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!--/.col (left) -->

            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

templates/basic/user_registration.html
{% extends 'basic/base.html' %} {% load static %} {% block content %}


<style>
    #myMap {
        height: 350px;
        width: 380px;
    }
</style>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDge58kDZRSDquz16IhEFQZMzHjMpFWwlw&callback=initMap&sensor=false">
</script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js">
</script>
<script type="text/javascript">
    var map;
    var marker;
    var myLatlng = new google.maps.LatLng(8.532897984777051, 76.95984865574053);
    var geocoder = new google.maps.Geocoder();
    var infowindow = new google.maps.InfoWindow();

    function initialize() {
        var mapOptions = {
            zoom: 18,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById("myMap"), mapOptions);

        marker = new google.maps.Marker({
            map: map,
            position: myLatlng,
            draggable: true
        });

        geocoder.geocode({
            'latLng': myLatlng
        }, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[0]) {
                    $('#latitude,#longitude').show();
                    $('#address').val(results[0].formatted_address);
                    $('#latitude').val(marker.getPosition().lat());
                    $('#longitude').val(marker.getPosition().lng());
                    infowindow.setContent(results[0].formatted_address);
                    infowindow.open(map, marker);
                }
            }
        });

        google.maps.event.addListener(marker, 'dragend', function() {

            geocoder.geocode({
                'latLng': marker.getPosition()
            }, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[0]) {
                        $('#address').val(results[0].formatted_address);
                        $('#latitude').val(marker.getPosition().lat());
                        $('#longitude').val(marker.getPosition().lng());
                        infowindow.setContent(results[0].formatted_address);
                        infowindow.open(map, marker);
                    }
                }
            });
        });

    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Register Your Account</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Municiplaity</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-4" id="myMap" style="border:4px double white;">

                </div>
                <div class="col-md-6">


                    <!-- general form elements -->

                    <!-- /.card -->
                    <!-- Horizontal Form -->
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">User Registration </h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form class="form-horizontal" method="POST" enctype="multipart/form-data" onsubmit="return validateForm()">
                            {% csrf_token %}

                            <div class="card-body">
                                <div class="form-group">
                                    <!-- <label for="exampleInputEmail1">Municiplaity</label> -->
                                    <input type="text"  name="name" class="form-control" id="exampleInputName" placeholder="Full Name">
                                </div>
                                <div class="form-group">
                                    <!-- <label for="exampleInputPassword1">Mayor</label> -->
                                    <input type="number"  required  name="phone" class="form-control" id="exampleInpuNumber" placeholder="Phone Number">
                                </div>
                                <div class="form-group">
                                    <!-- <label for="exampleInputPassword1">Mayor</label> -->
                                    <input type="file" name="photo" required class="form-control" >
                                </div>
                                <div class="form-group">
                                    <!-- <label for="exampleInputPassword1">Mayor</label> -->
                                    <textarea type="text" id="address" name="address" class="form-control" rows="4" placeholder="Address">
                                        </textarea>
                                </div>
                                <div class="form-group">
                                    <!-- <label for="username">Username</label> -->
                                    <input type="text" id="latitude" hidden name="latitude" class="form-control"placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <!-- <label for="username">Username</label> -->
                                    <input type="text" id="longitude"  hidden name="longitude" class="form-control"  placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <!-- <label for="exampleInputEmail1">Municiplaity</label> -->
                                    <input type="text"  name="municipality" class="form-control" id="exampleInputName" placeholder="Municipality">
                                </div>

                                <div class="form-group">
                                    <!-- <label for="username">Username</label> -->
                                    <input type="text"  name="username" class="form-control" id="exampleInputName" placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <!-- <label for="password">Password</label> -->
                                    <input type="password" name="password" class="form-control" id="exampleInputName" placeholder="Password">
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!--/.col (left) -->

            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


{% endblock %}