SmartCity_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
   path('',include('credentials.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,
                document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL,
                document_root=settings.MEDIA_ROOT)

Water_app/urls.py
from django.urls import path
from . import views


app_name ='water'


urlpatterns =[
    path('',views.index,name='index')

]

credentials/urls.py
from django.urls import path
from . import views



app_name='credentials'

urlpatterns = [
    
    path('',views.index,name='index'),
    path('signIn',views.signIn,name='signIn'),
    path('logout',views.logout,name='logout'),
    path('mypage',views.myfunction),
    path('method',views.method),
    path('demo',views.demo),

    #ADMIN
    path('Admin',views.admin_index,name='AdminHome'),
    path('addMuninicipality',views.addMuninicipality,name='addMuninicipality'),

    #Municipality
    path('municipality',views.municipalityHome,name='municipalityHome'),
    path('AddWasteBin',views.AddWasteBin,name='AddWasteBin'),
    path('AddCollectionAgent',views.AddCollectionAgent,name='AddCollectionAgent'),

    #Collection Agent
    path('Home',views.collectionAgent_home,name='collectionAgent_home'),


]

templates/municipality/AddCollectionAgent.html
{% extends 'basic/base.html' %} {% load static %} {% block content %}


<style>
    #myMap {
        height: 350px;
        width: 380px;
    }
</style>

<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDge58kDZRSDquz16IhEFQZMzHjMpFWwlw&callback=initMap&sensor=false">
    </script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js">
</script>
<script type="text/javascript">
    var map;
    var marker;
    var myLatlng = new google.maps.LatLng(8.532897984777051, 76.95984865574053);
    var geocoder = new google.maps.Geocoder();
    var infowindow = new google.maps.InfoWindow();

    function initialize() {
        var mapOptions = {
            zoom: 18,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById("myMap"), mapOptions);

        marker = new google.maps.Marker({
            map: map,
            position: myLatlng,
            draggable: true
        });

        geocoder.geocode({
            'latLng': myLatlng
        }, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[0]) {
                    $('#latitude,#longitude').show();
                    $('#address').val(results[0].formatted_address);
                    $('#latitude').val(marker.getPosition().lat());
                    $('#longitude').val(marker.getPosition().lng());
                    infowindow.setContent(results[0].formatted_address);
                    infowindow.open(map, marker);
                }
            }
        });

        google.maps.event.addListener(marker, 'dragend', function () {

            geocoder.geocode({
                'latLng': marker.getPosition()
            }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[0]) {
                        $('#address').val(results[0].formatted_address);
                        $('#latitude').val(marker.getPosition().lat());
                        $('#longitude').val(marker.getPosition().lng());
                        infowindow.setContent(results[0].formatted_address);
                        infowindow.open(map, marker);
                    }
                }
            });
        });

    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Garbage Collection Agent</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">

                        <li class="breadcrumb-item active">Collection Agent</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-4"  ></div>
                <div class="col-md-6">


                    <!-- general form elements -->

                    <!-- /.card -->
                    <!-- Horizontal Form -->
                    <div class="card card-info">
                        <div class="card-header" style="background-color: #FB5B38;">
                            <h3 class="card-title">Add Collection Agent </h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="card-body">
                                <div class="form-group">
                                    <!-- <label for="exampleInputEmail1">Municiplaity</label> -->
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                                        placeholder="Full Name">
                                </div>
                              
                         
                                <div class="form-group">
                                    <!-- <label for="exampleInputPassword1">Mayor</label> -->
                                    <input type="number" name="phone" class="form-control" placeholder="Phone">
                                </div>
                             
                                <div class="form-group">
                                    <!-- <label for="username">Username</label> -->
                                    <input type="file" name="photo" class="form-control" id="username"
                                        placeholder="">
                                </div>
                           
                               
                                <div class="form-group">
                                    <textarea type="text" name="address" class="form-control" rows="3" id="address"
                                        placeholder="Address">
                                        </textarea>
                                </div>
                             
                                <label>Vehicle Details</label>
                                <div class="form-group">
                                    <!-- <label for="exampleInputPassword1">Mayor</label> -->
                                    <input type="text" name="v_number" class="form-control" id="exampleInputPassword1"
                                        placeholder="Vehicle Number">
                                </div>
                                <div class="form-group">
                                    <label for="">Vehicle Image</label>
                                    <input type="file" name="v_image" class="form-control" id="username"
                                        placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <!-- <label for="username">Username</label> -->
                                    <input type="text" name="username" class="form-control" id="username"
                                        placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <!-- <label for="password">Password</label> -->
                                    <input type="password" name="password" class="form-control" id="password"
                                        placeholder="Password">
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn" style="background-color: #FB5B38;">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!--/.col (left) -->

            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

templates/municipality/AddWasteBin.html
{% extends 'basic/base.html' %} {% load static %} {% block content %}


<style>
    #myMap {
        height: 350px;
        width: 380px;
    }
</style>

    
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add New Waste Bin</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">

                        <li class="breadcrumb-item active">New Waste Bin</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-4" id="myMap" ></div>
                <div class="col-md-6">


                    <!-- general form elements -->

                    <!-- /.card -->
                    <!-- Horizontal Form -->
                    <div class="card card-info">
                        <div class="card-header" style="background-color: #FB5B38;">
                            <h3 class="card-title">New Waste Bin</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="card-body">
                                <div class="form-group">
                                    <!-- <label for="exampleInputEmail1">Municiplaity</label> -->
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                                        placeholder="Identity Word">
                                </div>
                                <div class="form-group">
                                    <label for="">Wastebin Image</label>
                                    <input type="file" name="photo" class="form-control" id="username"
                                        placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <label for="">Assign Collection agent</label>
                                    <select class="form-control" placeholder="Username">
                                        {% for agnt in agents %}
                                        <option value="{{agnt.id}}">
                                            {{agnt.name}}
                                        </option>
                                        {% endfor %}
                                        </select>
                                </div>
                                <label>Landmark</label>
                                <div class="form-group">
                                    <textarea type="text" name="address" class="form-control" rows="3" id="address"
                                        placeholder="LandMark">
                                        </textarea>
                                </div>
                                <div class="form-group">
                                    <!-- <label for="exampleInputPassword1">Mayor</label> -->
                                    <input type="text"  name="latitude" id="latitude" class="form-control"
                                        id="exampleInputPassword1">
                                </div>
                                <div class="form-group">
                                   
                                    <!-- <label for="exampleInputPassword1">Mayor</label> -->
                                    <input type="text"  name="longitude" id="longitude" class="form-control"
                                        id="exampleInputPassword1">
                                </div>
                                
                         
                               
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn" style="background-color: #FB5B38;">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!--/.col (left) -->

            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

{% endblock %}

templates/municipality/ViewUserFeedbacks.html
{% extends 'basic/base.html' %} {% load static %} {% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0">Dashboard</h1> -->
                </div>
                <!-- /.col -->
                <!-- <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div> -->
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
           
            <!-- Main row -->
            <div class="row">
                <section class="col-lg-1 connectedSortable"></section>
                <section class="col-lg-10 connectedSortable">
                    <!-- TABLE: LATEST ORDERS -->
                    <div class="card">
                        <div class="card-header border-transparent">
                            <h3 class="card-title">Latest Feedbacks</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-card-widget="remove">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table m-0">
                                    <thead>
                                        <tr>
                                            <th>Trip Id dd{{feedbacks.count}}</th>
                                            <th>User</th>
                                            <th>feessdback </th>
                                            <th> </th>
                                            <!-- <th>Status</th> -->
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for trp in feedbacks %}
                                        <tr>
                                            <td>{{trp.3}}</td>
                                            <td style="width: 100px;">
                                                <img src="media/{{trp.2}}" class="img-circle elevation-2" alt="User Image" style="width:70px">
                                                <b>{{trp.1|title}}</b></td>
                                            <td>"{{trp.0}}"</td>

                                            <td>
                                                <!-- <button class="btn btn-success" data-toggle="modal"
                                                    data-target="#feedback">Assign</button> -->
                                            </td>
                                        </tr>

                                     {% endfor %}
                            </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <a href="javascript:void(0)" class="btn btn-sm btn-info float-left">Refresh</a>
                        <a href="javascript:void(0)" class="btn btn-sm btn-secondary float-right">View All
                            Orders</a>
                    </div>
                    <!-- /.card-footer -->
            </div>
            <!-- /.card -->

    </section>
</div>
</div>
<!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% endblock %}

templates/municipality/municipality_navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'credentials:municipalityHome' %}" class="nav-link">Home</a>
        </li>
        
    </ul>

   
</nav>

templates/municipality/municipality_sidebar.html
{% load static %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-light-purple elevation-4">
    <!-- Brand Logo -->
    <!-- <a href="../../index3.html" class="brand-link">
        <img src="../../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">collection Agent 3</span>
    </a> -->

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{municipality.photo.url}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block"> {{municipality.municipality}}</a>
            </div>
        </div>



        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                <!-- <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="../../index.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v1</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../../index2.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v2</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../../index3.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Dashboard v3</p>
                            </a>
                        </li>
                    </ul>
                </li> -->
                <li class="nav-item">
                    <a href="{% url 'credentials:AddWasteBin' %}" class="nav-link">
                        <i class="ion ion-person-add"></i>
                        <p>
                        Add Waste Bin
                            <span class="right badge badge-danger">New</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'credentials:AddCollectionAgent' %}" class="nav-link">
                        <i class="ion ion-person-add"></i>
                        <p>
                            Add Collection Agents
                            <span class="right badge badge-danger">New</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            View Complaints
                            <i class="fas fa-angle-left right"></i>
                            <span class="badge badge-info right">{{complaint_count}}</span>
                        </p>
                    </a>
                 
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            Trip History
                            <i class="fas fa-angle-left right"></i>
                            <span class="badge badge-info right"></span>
                        </p>
                    </a>
                 
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            View Feedbacks
                            <i class="fas fa-angle-left right"></i>
                            <span class="badge badge-info right"></span>
                        </p>
                    </a>
                 
                </li>
                <!-- <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>
                            Charts
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="../charts/chartjs.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>ChartJS</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../charts/flot.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Flot</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../charts/inline.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Inline</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../charts/uplot.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>uPlot</p>
                            </a>
                        </li>
                    </ul>
                </li> -->
                <!-- <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tree"></i>
                        <p>
                            UI Elements
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="../UI/general.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>General</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../UI/icons.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Icons</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../UI/buttons.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Buttons</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../UI/sliders.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Sliders</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../UI/modals.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Modals & Alerts</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../UI/navbar.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Navbar & Tabs</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../UI/timeline.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Timeline</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../UI/ribbons.html" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Ribbons</p>
                            </a>
                        </li>
                    </ul>
                </li> -->

                <li class="nav-item">
                    <a href="{% url 'credentials:logout' %}" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            Logout
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>

                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>